//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @XRControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @XRControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Character"",
            ""id"": ""aba02f82-403e-4b09-9a7a-5672f25a1616"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""c6eb0e2c-409d-47c0-932e-3ffc2895ca9d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Turn"",
                    ""type"": ""Value"",
                    ""id"": ""07c87554-081b-4b22-b30e-5c08bad85764"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Summon Menu"",
                    ""type"": ""Button"",
                    ""id"": ""ceb9d580-9c0b-4663-a00f-fa2890046b9d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grab Left"",
                    ""type"": ""Value"",
                    ""id"": ""707e6fed-0b4c-4a73-a4d4-506c6be05193"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Grab Right"",
                    ""type"": ""Value"",
                    ""id"": ""78b6a329-2b9d-461f-9baa-f8ced9adff64"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Trigger Left"",
                    ""type"": ""Value"",
                    ""id"": ""082a8edf-e862-4cad-b122-61819481a6d8"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Trigger Right"",
                    ""type"": ""Value"",
                    ""id"": ""74a73175-1341-421a-92e8-0d87de9aebaf"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Primary Mode Left"",
                    ""type"": ""Button"",
                    ""id"": ""2d1b2303-9d00-47ee-b938-3bd53b0cfc8a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Primary Mode Right"",
                    ""type"": ""Button"",
                    ""id"": ""270ce23c-d17f-4837-9fb0-c4a99c71ad2a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Secondary Mode Left"",
                    ""type"": ""Button"",
                    ""id"": ""21862979-2d49-4ea6-9616-4c26c79508e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Secondary Mode Right"",
                    ""type"": ""Button"",
                    ""id"": ""1bcba56d-f0cb-4b90-8187-fad20b5e9394"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0124e059-8802-46dd-baa5-38f739f8d786"",
                    ""path"": ""<ValveIndexController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Index"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74c94016-fadf-45e5-85a0-beff04f03b75"",
                    ""path"": ""<ReverbG2Controller>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""HP Reverb G2"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c98f377a-8eb6-46d6-8e5a-35d7a8a2c583"",
                    ""path"": ""<ViveController>{LeftHand}/trackpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Vive"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e992bed1-33b1-4c7b-bfbd-ef09a7dc79d7"",
                    ""path"": ""<OculusTouchController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Oculus"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f8657c5-02b1-4cce-8b63-c2a743793d6d"",
                    ""path"": ""<ValveIndexController>{RightHand}/thumbstick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Index"",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1018f02-f4dc-4a39-a536-934eb4342c13"",
                    ""path"": ""<ReverbG2Controller>{RightHand}/thumbstick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""HP Reverb G2"",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b1adbf4-a74b-4d9d-a579-123440b1c9be"",
                    ""path"": ""<ViveController>{RightHand}/trackpad/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Vive"",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b6f7d83-e598-491b-a842-f5438e89a510"",
                    ""path"": ""<OculusTouchController>{RightHand}/thumbstick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Oculus"",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""363ec997-9f0e-4fdd-a90a-6e9db3f6cae5"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Index"",
                    ""action"": ""Summon Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81ccf39a-e478-4a6d-a6d8-947f17175ff3"",
                    ""path"": ""<ReverbG2Controller>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""HP Reverb G2"",
                    ""action"": ""Summon Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25a64d7c-15d4-479b-b543-4c26ca5c762d"",
                    ""path"": ""<ViveController>{LeftHand}/menu"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Vive"",
                    ""action"": ""Summon Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75499d05-72dc-4246-b6b9-0b4456f1df8e"",
                    ""path"": ""<ValveIndexController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Index"",
                    ""action"": ""Grab Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46e9d2d1-e071-40b7-a551-f5b7fec849c2"",
                    ""path"": ""<ViveController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Vive"",
                    ""action"": ""Grab Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35db8e01-524d-4b77-abf4-7b58f3396c47"",
                    ""path"": ""<OculusTouchController>{LeftHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Oculus"",
                    ""action"": ""Grab Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c567281d-7c9b-4c70-bbc0-08ce24ccb152"",
                    ""path"": ""<ValveIndexController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Index"",
                    ""action"": ""Grab Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""17583061-9f2e-4ab0-95e2-2398bbde0afc"",
                    ""path"": ""<ViveController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Vive"",
                    ""action"": ""Grab Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64a35526-9b1e-42b6-ba01-69ab293311aa"",
                    ""path"": ""<OculusTouchController>{RightHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Oculus"",
                    ""action"": ""Grab Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a98e2a7-6451-4478-8f48-4511f72ed9c2"",
                    ""path"": ""<ValveIndexController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Index"",
                    ""action"": ""Trigger Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e40fb484-9f92-4beb-b3f0-ef103f8c726b"",
                    ""path"": ""<ViveController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Vive"",
                    ""action"": ""Trigger Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d3470e5-6b75-4aeb-9015-f4f12ec10fea"",
                    ""path"": ""<OculusTouchController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Oculus"",
                    ""action"": ""Trigger Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""805932b3-bfcf-4473-8129-f4bd214b34ef"",
                    ""path"": ""<ValveIndexController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Index"",
                    ""action"": ""Trigger Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd3c13b6-3b02-4935-ab8b-3bf3544c8b06"",
                    ""path"": ""<ViveController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Vive"",
                    ""action"": ""Trigger Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd1cd25a-0717-44a3-9285-1af9b3ca3efa"",
                    ""path"": ""<OculusTouchController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Oculus"",
                    ""action"": ""Trigger Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""403789f3-8ab9-46fc-a66a-d14ad73985d7"",
                    ""path"": ""<OculusTouchController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Oculus"",
                    ""action"": ""Primary Mode Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63659e16-1f33-4019-862f-4bfaff8acefe"",
                    ""path"": ""<ValveIndexController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Index"",
                    ""action"": ""Primary Mode Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd515031-74a6-44eb-b96e-dd0a0e2c50b4"",
                    ""path"": ""<XRInputV1::HTC::HTCViveControllerOpenXR>{LeftHand}/menu"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Vive"",
                    ""action"": ""Primary Mode Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0fb62178-6c08-4c1f-b92f-79a956550da1"",
                    ""path"": ""<OculusTouchController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Oculus"",
                    ""action"": ""Primary Mode Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0a3ea37-8eda-4c55-a47c-e8f91e6648b5"",
                    ""path"": ""<OculusTouchController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Oculus"",
                    ""action"": ""Secondary Mode Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57e6a7da-c3d3-4176-8ee2-41220ef58713"",
                    ""path"": ""<OculusTouchController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Oculus"",
                    ""action"": ""Secondary Mode Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c629e4a3-a26d-4b5d-b3c6-605159464def"",
                    ""path"": ""<ValveIndexController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Index"",
                    ""action"": ""Primary Mode Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25c40346-7b77-438e-b124-06017be38ec1"",
                    ""path"": ""<ViveController>{RightHand}/menu"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Vive"",
                    ""action"": ""Primary Mode Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76b02314-14ec-41ff-afea-306013613217"",
                    ""path"": ""<ValveIndexController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Index"",
                    ""action"": ""Secondary Mode Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c3e6e76-d7e8-4c06-a6d1-cbca95852fce"",
                    ""path"": ""<ValveIndexController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Index"",
                    ""action"": ""Secondary Mode Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Menu"",
            ""id"": ""5b41407e-280c-45ca-bc42-8d526d6ad5a6"",
            ""actions"": [
                {
                    ""name"": ""Select"",
                    ""type"": ""Value"",
                    ""id"": ""d67012ba-330b-4bd5-ac0f-1907cfbd01f9"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Exit"",
                    ""type"": ""Button"",
                    ""id"": ""51340201-3328-43c6-bbf5-dc6cf91fa22c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d367067a-6a95-4c22-bfb8-5b06137ffc45"",
                    ""path"": ""<ValveIndexController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Index"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20cf488b-853a-4188-ac76-eed5c0965ab2"",
                    ""path"": ""<ValveIndexController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Index"",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f72501c0-2296-44ed-95de-683aefc9df7c"",
                    ""path"": ""<OculusTouchController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Oculus"",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c2100d0-0f70-4a21-9d49-57ab34c633c0"",
                    ""path"": ""<ReverbG2Controller>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""HP Reverb G2"",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Index"",
            ""bindingGroup"": ""Index"",
            ""devices"": [
                {
                    ""devicePath"": ""<ValveIndexController>{LeftHand}"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<ValveIndexController>{RightHand}"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""HP Reverb G2"",
            ""bindingGroup"": ""HP Reverb G2"",
            ""devices"": [
                {
                    ""devicePath"": ""<ReverbG2Controller>{LeftHand}"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<ReverbG2Controller>{RightHand}"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Vive"",
            ""bindingGroup"": ""Vive"",
            ""devices"": [
                {
                    ""devicePath"": ""<ViveController>{LeftHand}"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<ViveController>{RightHand}"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Oculus"",
            ""bindingGroup"": ""Oculus"",
            ""devices"": [
                {
                    ""devicePath"": ""<OculusTouchController>{LeftHand}"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<OculusTouchController>{RightHand}"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Character
        m_Character = asset.FindActionMap("Character", throwIfNotFound: true);
        m_Character_Move = m_Character.FindAction("Move", throwIfNotFound: true);
        m_Character_Turn = m_Character.FindAction("Turn", throwIfNotFound: true);
        m_Character_SummonMenu = m_Character.FindAction("Summon Menu", throwIfNotFound: true);
        m_Character_GrabLeft = m_Character.FindAction("Grab Left", throwIfNotFound: true);
        m_Character_GrabRight = m_Character.FindAction("Grab Right", throwIfNotFound: true);
        m_Character_TriggerLeft = m_Character.FindAction("Trigger Left", throwIfNotFound: true);
        m_Character_TriggerRight = m_Character.FindAction("Trigger Right", throwIfNotFound: true);
        m_Character_PrimaryModeLeft = m_Character.FindAction("Primary Mode Left", throwIfNotFound: true);
        m_Character_PrimaryModeRight = m_Character.FindAction("Primary Mode Right", throwIfNotFound: true);
        m_Character_SecondaryModeLeft = m_Character.FindAction("Secondary Mode Left", throwIfNotFound: true);
        m_Character_SecondaryModeRight = m_Character.FindAction("Secondary Mode Right", throwIfNotFound: true);
        // Menu
        m_Menu = asset.FindActionMap("Menu", throwIfNotFound: true);
        m_Menu_Select = m_Menu.FindAction("Select", throwIfNotFound: true);
        m_Menu_Exit = m_Menu.FindAction("Exit", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Character
    private readonly InputActionMap m_Character;
    private List<ICharacterActions> m_CharacterActionsCallbackInterfaces = new List<ICharacterActions>();
    private readonly InputAction m_Character_Move;
    private readonly InputAction m_Character_Turn;
    private readonly InputAction m_Character_SummonMenu;
    private readonly InputAction m_Character_GrabLeft;
    private readonly InputAction m_Character_GrabRight;
    private readonly InputAction m_Character_TriggerLeft;
    private readonly InputAction m_Character_TriggerRight;
    private readonly InputAction m_Character_PrimaryModeLeft;
    private readonly InputAction m_Character_PrimaryModeRight;
    private readonly InputAction m_Character_SecondaryModeLeft;
    private readonly InputAction m_Character_SecondaryModeRight;
    public struct CharacterActions
    {
        private @XRControls m_Wrapper;
        public CharacterActions(@XRControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Character_Move;
        public InputAction @Turn => m_Wrapper.m_Character_Turn;
        public InputAction @SummonMenu => m_Wrapper.m_Character_SummonMenu;
        public InputAction @GrabLeft => m_Wrapper.m_Character_GrabLeft;
        public InputAction @GrabRight => m_Wrapper.m_Character_GrabRight;
        public InputAction @TriggerLeft => m_Wrapper.m_Character_TriggerLeft;
        public InputAction @TriggerRight => m_Wrapper.m_Character_TriggerRight;
        public InputAction @PrimaryModeLeft => m_Wrapper.m_Character_PrimaryModeLeft;
        public InputAction @PrimaryModeRight => m_Wrapper.m_Character_PrimaryModeRight;
        public InputAction @SecondaryModeLeft => m_Wrapper.m_Character_SecondaryModeLeft;
        public InputAction @SecondaryModeRight => m_Wrapper.m_Character_SecondaryModeRight;
        public InputActionMap Get() { return m_Wrapper.m_Character; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterActions set) { return set.Get(); }
        public void AddCallbacks(ICharacterActions instance)
        {
            if (instance == null || m_Wrapper.m_CharacterActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CharacterActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Turn.started += instance.OnTurn;
            @Turn.performed += instance.OnTurn;
            @Turn.canceled += instance.OnTurn;
            @SummonMenu.started += instance.OnSummonMenu;
            @SummonMenu.performed += instance.OnSummonMenu;
            @SummonMenu.canceled += instance.OnSummonMenu;
            @GrabLeft.started += instance.OnGrabLeft;
            @GrabLeft.performed += instance.OnGrabLeft;
            @GrabLeft.canceled += instance.OnGrabLeft;
            @GrabRight.started += instance.OnGrabRight;
            @GrabRight.performed += instance.OnGrabRight;
            @GrabRight.canceled += instance.OnGrabRight;
            @TriggerLeft.started += instance.OnTriggerLeft;
            @TriggerLeft.performed += instance.OnTriggerLeft;
            @TriggerLeft.canceled += instance.OnTriggerLeft;
            @TriggerRight.started += instance.OnTriggerRight;
            @TriggerRight.performed += instance.OnTriggerRight;
            @TriggerRight.canceled += instance.OnTriggerRight;
            @PrimaryModeLeft.started += instance.OnPrimaryModeLeft;
            @PrimaryModeLeft.performed += instance.OnPrimaryModeLeft;
            @PrimaryModeLeft.canceled += instance.OnPrimaryModeLeft;
            @PrimaryModeRight.started += instance.OnPrimaryModeRight;
            @PrimaryModeRight.performed += instance.OnPrimaryModeRight;
            @PrimaryModeRight.canceled += instance.OnPrimaryModeRight;
            @SecondaryModeLeft.started += instance.OnSecondaryModeLeft;
            @SecondaryModeLeft.performed += instance.OnSecondaryModeLeft;
            @SecondaryModeLeft.canceled += instance.OnSecondaryModeLeft;
            @SecondaryModeRight.started += instance.OnSecondaryModeRight;
            @SecondaryModeRight.performed += instance.OnSecondaryModeRight;
            @SecondaryModeRight.canceled += instance.OnSecondaryModeRight;
        }

        private void UnregisterCallbacks(ICharacterActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Turn.started -= instance.OnTurn;
            @Turn.performed -= instance.OnTurn;
            @Turn.canceled -= instance.OnTurn;
            @SummonMenu.started -= instance.OnSummonMenu;
            @SummonMenu.performed -= instance.OnSummonMenu;
            @SummonMenu.canceled -= instance.OnSummonMenu;
            @GrabLeft.started -= instance.OnGrabLeft;
            @GrabLeft.performed -= instance.OnGrabLeft;
            @GrabLeft.canceled -= instance.OnGrabLeft;
            @GrabRight.started -= instance.OnGrabRight;
            @GrabRight.performed -= instance.OnGrabRight;
            @GrabRight.canceled -= instance.OnGrabRight;
            @TriggerLeft.started -= instance.OnTriggerLeft;
            @TriggerLeft.performed -= instance.OnTriggerLeft;
            @TriggerLeft.canceled -= instance.OnTriggerLeft;
            @TriggerRight.started -= instance.OnTriggerRight;
            @TriggerRight.performed -= instance.OnTriggerRight;
            @TriggerRight.canceled -= instance.OnTriggerRight;
            @PrimaryModeLeft.started -= instance.OnPrimaryModeLeft;
            @PrimaryModeLeft.performed -= instance.OnPrimaryModeLeft;
            @PrimaryModeLeft.canceled -= instance.OnPrimaryModeLeft;
            @PrimaryModeRight.started -= instance.OnPrimaryModeRight;
            @PrimaryModeRight.performed -= instance.OnPrimaryModeRight;
            @PrimaryModeRight.canceled -= instance.OnPrimaryModeRight;
            @SecondaryModeLeft.started -= instance.OnSecondaryModeLeft;
            @SecondaryModeLeft.performed -= instance.OnSecondaryModeLeft;
            @SecondaryModeLeft.canceled -= instance.OnSecondaryModeLeft;
            @SecondaryModeRight.started -= instance.OnSecondaryModeRight;
            @SecondaryModeRight.performed -= instance.OnSecondaryModeRight;
            @SecondaryModeRight.canceled -= instance.OnSecondaryModeRight;
        }

        public void RemoveCallbacks(ICharacterActions instance)
        {
            if (m_Wrapper.m_CharacterActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICharacterActions instance)
        {
            foreach (var item in m_Wrapper.m_CharacterActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CharacterActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CharacterActions @Character => new CharacterActions(this);

    // Menu
    private readonly InputActionMap m_Menu;
    private List<IMenuActions> m_MenuActionsCallbackInterfaces = new List<IMenuActions>();
    private readonly InputAction m_Menu_Select;
    private readonly InputAction m_Menu_Exit;
    public struct MenuActions
    {
        private @XRControls m_Wrapper;
        public MenuActions(@XRControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Select => m_Wrapper.m_Menu_Select;
        public InputAction @Exit => m_Wrapper.m_Menu_Exit;
        public InputActionMap Get() { return m_Wrapper.m_Menu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuActions set) { return set.Get(); }
        public void AddCallbacks(IMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_MenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MenuActionsCallbackInterfaces.Add(instance);
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @Exit.started += instance.OnExit;
            @Exit.performed += instance.OnExit;
            @Exit.canceled += instance.OnExit;
        }

        private void UnregisterCallbacks(IMenuActions instance)
        {
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @Exit.started -= instance.OnExit;
            @Exit.performed -= instance.OnExit;
            @Exit.canceled -= instance.OnExit;
        }

        public void RemoveCallbacks(IMenuActions instance)
        {
            if (m_Wrapper.m_MenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_MenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MenuActions @Menu => new MenuActions(this);
    private int m_IndexSchemeIndex = -1;
    public InputControlScheme IndexScheme
    {
        get
        {
            if (m_IndexSchemeIndex == -1) m_IndexSchemeIndex = asset.FindControlSchemeIndex("Index");
            return asset.controlSchemes[m_IndexSchemeIndex];
        }
    }
    private int m_HPReverbG2SchemeIndex = -1;
    public InputControlScheme HPReverbG2Scheme
    {
        get
        {
            if (m_HPReverbG2SchemeIndex == -1) m_HPReverbG2SchemeIndex = asset.FindControlSchemeIndex("HP Reverb G2");
            return asset.controlSchemes[m_HPReverbG2SchemeIndex];
        }
    }
    private int m_ViveSchemeIndex = -1;
    public InputControlScheme ViveScheme
    {
        get
        {
            if (m_ViveSchemeIndex == -1) m_ViveSchemeIndex = asset.FindControlSchemeIndex("Vive");
            return asset.controlSchemes[m_ViveSchemeIndex];
        }
    }
    private int m_OculusSchemeIndex = -1;
    public InputControlScheme OculusScheme
    {
        get
        {
            if (m_OculusSchemeIndex == -1) m_OculusSchemeIndex = asset.FindControlSchemeIndex("Oculus");
            return asset.controlSchemes[m_OculusSchemeIndex];
        }
    }
    public interface ICharacterActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnTurn(InputAction.CallbackContext context);
        void OnSummonMenu(InputAction.CallbackContext context);
        void OnGrabLeft(InputAction.CallbackContext context);
        void OnGrabRight(InputAction.CallbackContext context);
        void OnTriggerLeft(InputAction.CallbackContext context);
        void OnTriggerRight(InputAction.CallbackContext context);
        void OnPrimaryModeLeft(InputAction.CallbackContext context);
        void OnPrimaryModeRight(InputAction.CallbackContext context);
        void OnSecondaryModeLeft(InputAction.CallbackContext context);
        void OnSecondaryModeRight(InputAction.CallbackContext context);
    }
    public interface IMenuActions
    {
        void OnSelect(InputAction.CallbackContext context);
        void OnExit(InputAction.CallbackContext context);
    }
}
